# Generated by Django 4.2.3 on 2023-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
