# Generated by Django 4.2.3 on 2023-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
