# Generated by Django 3.1.2 on 2021-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone_number', models.CharField(max_length=15)),
                ('patient_city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(default='336867', max_length=6)),
                ('patient_report', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
