# Generated by Django 3.2.11 on 2022-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220109_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='patient_chasing_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
